import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { signIn, signOut, useSession, getSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

const { data: session, status } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.holder}>
          <div className={styles.left}>
            <span className={styles.logo} onClick={signIn} >
              <Image src="/vercel.svg" alt="logo" width={90} height={20} />
            </span>
            
          </div>
          <div className={styles.right}>
            <Image src="/login_img.png" alt="login_image" fill={true}/>
          </div>
        </div>
        <div className={styles.boxShadow}></div>
      </main>
    </>
  )
}

export async function getServerSideProps (context) {
  const session = await getSession(context)
  
  return {
    props: { session }
  }
}