import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { getSession, signIn } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.holder}>
          <div className={styles.left}>
            <span className={styles.logo} onClick={() => signIn()} >
              <Image src="/vercel.svg" alt="logo" width={90} height={20} />
            </span>
            
          </div>
          <div className={styles.right}>
            <Image src="/login_img.png" alt="login_image" fill={true}/>
          </div>
        </div>
        <div className={styles.boxShadow}></div>
      </main>
    </>
  )
}

export async function getServerSideProps(context:any) {
  // Defines interface mySession with the user object
  interface mySession {
    user: {
      name?: string;
      email?: string;
      image?: string;
      role?: string;
      isNewUser?: boolean;
    };
  }

  const {req,res} = context
  const session = await (getSession({req}) as Promise<mySession>)

  if(session && res){
    if(session.user.isNewUser){
      res.writeHead(302, { Location: `/signup?provider=google` })
      res.end()
    } else {
      res.writeHead(302, { Location: `/${session?.user?.role}/dashboard` })
      res.end()
    }
  }
}